services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "9001:9001"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "gem install jekyll-feed jekyll-sitemap kramdown rouge webrick && jekyll serve --port 9001 --watch --force_polling"
